/*
---------------------
DO NOT EDIT THIS FILE
---------------------
*/

// The url of the geographical data server used
export const mapServerUrl = process.env.REACT_APP_GEOSERVER_URL;

// The layer in geoserver is always in the format <WORKSPACE>:<LAYER_NAME>
export const mapServerWorkspaceName = process.env.REACT_APP_GEOSERVER_WORKSPACE_NAME;

// WMS version of the geographical server link
export const mapServerWmsUrl = `${mapServerUrl}/wms`;

// geoConfigExporter.ts

if (!mapServerUrl) {
  throw new Error('REACT_APP_GEOSERVER_URL is not defined in environment variables.');
}

if (!mapServerWorkspaceName) {
  throw new Error('REACT_APP_GEOSERVER_WORKSPACE_NAME is not defined in environment variables.');
}

export type ChemicalElementLayerConfig = {
  layer: string;
  min: number;
  max: number;
}

export type ChemicalElementsLayer = {
  [element: string]: {
    [key: string]: ChemicalElementLayerConfig;
  };
};


export type LayersConfig = {
  chemicalElementLayer: ChemicalElementsLayer;
};


import layersConfigJson from './layersConfig.json';

export const layersConfig: LayersConfig = layersConfigJson;